@safe-vault_HostAddress = http://localhost:5181

GET {{safe-vault_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{safe-vault_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "alice",
  "password": "P@ssw0rd!"
}

###
